"""Torznab indexer.

Implements just enough of the Torznab spec for Sonarr/Radarr/Prowlarr to treat
this as a real indexer:

- t=caps         → capability XML
- t=tvsearch     → RSS feed of episode releases for a TV query
- t=movie        → RSS feed of movie releases
- t=search       → generic fallback (returns nothing useful unless query has IDs)

Our "releases" are magnets generated by jobs.make_magnet(), each encoding the
TMDB id + season/episode. The fake download client (fakeqbt.py) decodes them
to drive the scraper.
"""
from __future__ import annotations

import datetime as dt
import os
import urllib.parse
import urllib.request
from email.utils import format_datetime
from typing import Any
from xml.sax.saxutils import escape

from fastapi import APIRouter, Query, Response

from .jobs import make_magnet

router = APIRouter()

CAT_TV = "5000"
CAT_MOVIE = "2000"

# Bitrates we advertise per quality, in kilobits per second. Sonarr uses
# the resulting size estimates against its profile's size-per-minute caps,
# so these need to land inside typical 1080p WEBDL bands (~80-110 MB/min).
QUALITY_KBPS = {"360p": 800, "720p": 2500, "1080p": 5500}
DEFAULT_KBPS = QUALITY_KBPS["1080p"]
# Fallback runtimes (minutes) used when TMDB doesn't have one.
FALLBACK_EP_RUNTIME = 45
FALLBACK_MOVIE_RUNTIME = 110


def _size_bytes(quality: str, runtime_min: float | int) -> int:
    """bytes ≈ kbps * 125 (bytes/sec) * 60 (sec/min) * minutes."""
    kbps = QUALITY_KBPS.get(quality, DEFAULT_KBPS)
    return int(kbps * 125 * 60 * max(1, runtime_min))

INDEXER_TITLE = os.environ.get("WSG_INDEXER_TITLE", "WatchSeries.bar")


@router.get("/api")
def torznab_api(
    t: str = Query(...),
    q: str | None = None,
    tmdbid: str | None = None,
    tvdbid: str | None = None,
    imdbid: str | None = None,
    season: int | None = None,
    ep: int | None = None,
    cat: str | None = None,
    apikey: str | None = None,
    extended: int | None = None,
    limit: int | None = None,
    offset: int | None = None,
):
    if t == "caps":
        return _xml_response(_caps_xml())
    if t == "tvsearch":
        items = _tv_search(q, tmdbid, tvdbid, imdbid, season, ep)
        return _xml_response(_rss(items))
    if t == "movie":
        items = _movie_search(q, tmdbid, imdbid)
        return _xml_response(_rss(items))
    if t == "search":
        items = _generic_search(q, tmdbid, tvdbid, imdbid)
        return _xml_response(_rss(items))
    return _xml_response(_rss([]))


# ---- search implementations ----

def _tv_search(q, tmdbid, tvdbid, imdbid, season, ep) -> list[dict]:
    tmdb_id = tmdbid or _tmdb_from_tvdb(tvdbid) or _tmdb_from_imdb(imdbid)
    runtime = FALLBACK_EP_RUNTIME
    if not tmdb_id and q:
        tmdb_id, title, year, runtime = _tmdb_search_tv(q)
    else:
        if tmdb_id:
            title, year, runtime = _tmdb_details_tv(tmdb_id)
        else:
            title, year = (q or ""), ""

    if not tmdb_id:
        if not q:
            return [_test_release(CAT_TV)]
        return []
    title = title or q or f"tmdb-{tmdb_id}"

    items: list[dict] = []
    if season is not None and ep is not None:
        items.append(_episode_release(tmdb_id, title, year, season, ep, runtime))
    elif season is not None:
        ep_count = _tmdb_season_count(tmdb_id, season) or 12
        items.append(_season_pack_release(
            tmdb_id, title, year, season, runtime, ep_count))
    else:
        season_counts = _tmdb_series_episode_counts(tmdb_id)
        items.append(_series_release(
            tmdb_id, title, year, runtime,
            total_eps=sum(season_counts) if season_counts else 50))
    return items


def _movie_search(q, tmdbid, imdbid) -> list[dict]:
    tmdb_id = tmdbid or _tmdb_from_imdb(imdbid)
    runtime = FALLBACK_MOVIE_RUNTIME
    if not tmdb_id and q:
        tmdb_id, title, year, runtime = _tmdb_search_movie(q)
    else:
        if tmdb_id:
            title, year, runtime = _tmdb_details_movie(tmdb_id)
        else:
            title, year = (q or ""), ""
    if not tmdb_id:
        if not q:
            return [_test_release(CAT_MOVIE)]
        return []
    title = title or q or f"tmdb-{tmdb_id}"
    return [_movie_release(tmdb_id, title, year, runtime)]


def _generic_search(q, tmdbid, tvdbid, imdbid) -> list[dict]:
    out: list[dict] = []
    out += _tv_search(q, tmdbid, tvdbid, imdbid, None, None)
    out += _movie_search(q, tmdbid, imdbid)
    return out


# ---- release builders ----

def _episode_release(tmdb_id: str, title: str, year: str,
                     season: int, episode: int, runtime_min: int) -> dict:
    name = _release_name(title, year, season=season, episode=episode)
    magnet = make_magnet("tv", tmdb_id, title, season=season, episode=episode)
    return {
        "title": name,
        "guid": f"watchseries:tv:{tmdb_id}:s{season}e{episode}",
        "link": magnet,
        "size": _size_bytes("1080p", runtime_min),
        "category": CAT_TV,
        "pubDate": dt.datetime.now(dt.timezone.utc),
        "attrs": {"tmdb": tmdb_id, "season": season, "episode": episode},
    }


def _season_pack_release(tmdb_id: str, title: str, year: str, season: int,
                         runtime_min: int, ep_count: int) -> dict:
    name = _release_name(title, year, season=season)
    magnet = make_magnet("tv", tmdb_id, title, season=season)
    return {
        "title": name,
        "guid": f"watchseries:tv:{tmdb_id}:s{season}",
        "link": magnet,
        "size": _size_bytes("1080p", runtime_min * ep_count),
        "category": CAT_TV,
        "pubDate": dt.datetime.now(dt.timezone.utc),
        "attrs": {"tmdb": tmdb_id, "season": season},
    }


def _series_release(tmdb_id: str, title: str, year: str,
                    runtime_min: int, total_eps: int) -> dict:
    name = _release_name(title, year) + ".COMPLETE"
    magnet = make_magnet("tv", tmdb_id, title)
    return {
        "title": name,
        "guid": f"watchseries:tv:{tmdb_id}:all",
        "link": magnet,
        "size": _size_bytes("1080p", runtime_min * total_eps),
        "category": CAT_TV,
        "pubDate": dt.datetime.now(dt.timezone.utc),
        "attrs": {"tmdb": tmdb_id},
    }


def _movie_release(tmdb_id: str, title: str, year: str,
                   runtime_min: int) -> dict:
    name = _release_name(title, year, is_movie=True)
    magnet = make_magnet("movie", tmdb_id, title)
    return {
        "title": name,
        "guid": f"watchseries:movie:{tmdb_id}",
        "link": magnet,
        "size": _size_bytes("1080p", runtime_min),
        "category": CAT_MOVIE,
        "pubDate": dt.datetime.now(dt.timezone.utc),
        "attrs": {"tmdb": tmdb_id},
    }


def _test_release(category: str) -> dict:
    """A no-op placeholder release returned for empty test queries so
    Prowlarr/Sonarr see ≥1 result and consider the indexer healthy.
    Adding it as a real candidate to Sonarr would no-op cleanly — the
    fake-qBittorrent layer accepts the magnet, kicks off a job that finds
    no sources for tmdb=0, and ends in STATE_ERROR.
    """
    return {
        "title": "watchseries-grabber.indexer.online.TEST",
        "guid": "watchseries:test",
        "link": make_magnet("tv", "0", "indexer-test",
                            season=1, episode=1, quality="360p"),
        "size": 1,
        "category": category,
        "pubDate": dt.datetime.now(dt.timezone.utc),
        "attrs": {"test": "1"},
    }


def _release_name(title: str, year: str, *, season: int | None = None,
                  episode: int | None = None, is_movie: bool = False) -> str:
    base = title.replace(" ", ".")
    parts = [base]
    if year:
        parts.append(str(year))
    if not is_movie and season is not None and episode is not None:
        parts.append(f"S{season:02d}E{episode:02d}")
    elif not is_movie and season is not None:
        parts.append(f"S{season:02d}")
    parts += ["1080p", "WEBDL", "x264-WATCHSERIES"]
    return ".".join(parts)


# ---- TMDB lookups (optional, requires TMDB_API_KEY env var) ----

def _tmdb_api(path: str, params: dict[str, Any]) -> dict | None:
    key = os.environ.get("TMDB_API_KEY", "")
    if not key:
        return None
    params = {"api_key": key, **params}
    url = f"https://api.themoviedb.org/3{path}?{urllib.parse.urlencode(params)}"
    try:
        with urllib.request.urlopen(url, timeout=15) as r:
            import json
            return json.loads(r.read())
    except Exception:
        return None


def _tmdb_from_tvdb(tvdbid: str | None) -> str | None:
    if not tvdbid:
        return None
    d = _tmdb_api(f"/find/{tvdbid}", {"external_source": "tvdb_id"})
    if not d:
        return None
    results = d.get("tv_results", [])
    if results:
        return str(results[0]["id"])
    return None


def _tmdb_from_imdb(imdbid: str | None) -> str | None:
    if not imdbid:
        return None
    d = _tmdb_api(f"/find/{imdbid}", {"external_source": "imdb_id"})
    if not d:
        return None
    for k in ("tv_results", "movie_results"):
        if d.get(k):
            return str(d[k][0]["id"])
    return None


def _tmdb_search_tv(q: str) -> tuple[str | None, str, str, int]:
    d = _tmdb_api("/search/tv", {"query": q})
    if not d or not d.get("results"):
        return None, q, "", FALLBACK_EP_RUNTIME
    r = d["results"][0]
    tmdb_id = str(r["id"])
    # Search results don't include runtime; fetch details for that.
    _, _, runtime = _tmdb_details_tv(tmdb_id)
    return tmdb_id, r.get("name", q), (r.get("first_air_date") or "")[:4], runtime


def _tmdb_search_movie(q: str) -> tuple[str | None, str, str, int]:
    d = _tmdb_api("/search/movie", {"query": q})
    if not d or not d.get("results"):
        return None, q, "", FALLBACK_MOVIE_RUNTIME
    r = d["results"][0]
    tmdb_id = str(r["id"])
    _, _, runtime = _tmdb_details_movie(tmdb_id)
    return tmdb_id, r.get("title", q), (r.get("release_date") or "")[:4], runtime


def _tmdb_details_tv(tmdb_id: str) -> tuple[str, str, int]:
    d = _tmdb_api(f"/tv/{tmdb_id}", {})
    if not d:
        return "", "", FALLBACK_EP_RUNTIME
    rt = d.get("episode_run_time") or []
    runtime = int(rt[0]) if rt else FALLBACK_EP_RUNTIME
    return d.get("name", ""), (d.get("first_air_date") or "")[:4], runtime


def _tmdb_details_movie(tmdb_id: str) -> tuple[str, str, int]:
    d = _tmdb_api(f"/movie/{tmdb_id}", {})
    if not d:
        return "", "", FALLBACK_MOVIE_RUNTIME
    runtime = int(d.get("runtime") or FALLBACK_MOVIE_RUNTIME)
    return d.get("title", ""), (d.get("release_date") or "")[:4], runtime


def _tmdb_season_count(tmdb_id: str, season: int) -> int | None:
    d = _tmdb_api(f"/tv/{tmdb_id}/season/{season}", {})
    eps = d.get("episodes") if d else None
    return len(eps) if eps else None


def _tmdb_series_episode_counts(tmdb_id: str) -> list[int]:
    """Return [N_eps_s1, N_eps_s2, ...] for use in series-wide size estimates."""
    d = _tmdb_api(f"/tv/{tmdb_id}", {})
    if not d:
        return []
    out = []
    for s in d.get("seasons", []):
        n = s.get("episode_count")
        if s.get("season_number", 0) > 0 and n:
            out.append(int(n))
    return out


# ---- XML rendering ----

def _xml_response(body: str) -> Response:
    return Response(content=body, media_type="application/rss+xml; charset=utf-8")


def _caps_xml() -> str:
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<caps>
  <server title="{escape(INDEXER_TITLE)}"/>
  <limits max="100" default="50"/>
  <searching>
    <search available="yes" supportedParams="q"/>
    <tv-search available="yes" supportedParams="q,tvdbid,tmdbid,imdbid,season,ep"/>
    <movie-search available="yes" supportedParams="q,tmdbid,imdbid"/>
  </searching>
  <categories>
    <category id="2000" name="Movies">
      <subcat id="2040" name="Movies/HD"/>
    </category>
    <category id="5000" name="TV">
      <subcat id="5040" name="TV/HD"/>
    </category>
  </categories>
</caps>
"""


def _rss(items: list[dict]) -> str:
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<rss version="2.0" xmlns:torznab="http://torznab.com/schemas/2015/feed">',
        '<channel>',
        f'<title>{escape(INDEXER_TITLE)}</title>',
        '<description>watchseries.bar via Torznab</description>',
        '<link>https://watchseries.bar/</link>',
    ]
    for it in items:
        parts.append(_rss_item(it))
    parts.append('</channel></rss>')
    return "\n".join(parts)


def _rss_item(it: dict) -> str:
    pub = format_datetime(it["pubDate"])
    enclosure_url = escape(it["link"])
    attrs = it.get("attrs", {})
    attr_xml = "".join(
        f'<torznab:attr name="{k}" value="{escape(str(v))}"/>'
        for k, v in attrs.items()
    )
    return f"""<item>
<title>{escape(it["title"])}</title>
<guid isPermaLink="false">{escape(it["guid"])}</guid>
<link>{enclosure_url}</link>
<pubDate>{pub}</pubDate>
<size>{it["size"]}</size>
<category>{escape(it["category"])}</category>
<enclosure url="{enclosure_url}" length="{it["size"]}" type="application/x-bittorrent"/>
<torznab:attr name="category" value="{escape(it["category"])}"/>
<torznab:attr name="size" value="{it["size"]}"/>
{attr_xml}
</item>"""
