"""Torznab indexer.

Implements just enough of the Torznab spec for Sonarr/Radarr/Prowlarr to treat
this as a real indexer:

- t=caps         → capability XML
- t=tvsearch     → RSS feed of episode releases for a TV query
- t=movie        → RSS feed of movie releases
- t=search       → generic fallback (returns nothing useful unless query has IDs)

Our "releases" are magnets generated by jobs.make_magnet(), each encoding the
TMDB id + season/episode. The fake download client (fakeqbt.py) decodes them
to drive the scraper.
"""
from __future__ import annotations

import datetime as dt
import os
import urllib.parse
import urllib.request
from email.utils import format_datetime
from typing import Any
from xml.sax.saxutils import escape

from fastapi import APIRouter, Query, Response

from .jobs import make_magnet

router = APIRouter()

CAT_TV = "5000"
CAT_MOVIE = "2000"

# Estimated sizes Sonarr will see in the RSS (bytes). Sonarr uses these for
# quality decisions; we make them roughly correspond to 1080p WEBDL sizes.
SIZE_EPISODE = 1_500_000_000        # ~1.5GB per episode at 1080p
SIZE_SEASON = 15_000_000_000        # ~15GB for a season pack
SIZE_MOVIE = 4_000_000_000          # ~4GB for a movie

INDEXER_TITLE = os.environ.get("WSG_INDEXER_TITLE", "WatchSeries.bar")


@router.get("/api")
def torznab_api(
    t: str = Query(...),
    q: str | None = None,
    tmdbid: str | None = None,
    tvdbid: str | None = None,
    imdbid: str | None = None,
    season: int | None = None,
    ep: int | None = None,
    cat: str | None = None,
    apikey: str | None = None,
    extended: int | None = None,
    limit: int | None = None,
    offset: int | None = None,
):
    if t == "caps":
        return _xml_response(_caps_xml())
    if t == "tvsearch":
        items = _tv_search(q, tmdbid, tvdbid, imdbid, season, ep)
        return _xml_response(_rss(items))
    if t == "movie":
        items = _movie_search(q, tmdbid, imdbid)
        return _xml_response(_rss(items))
    if t == "search":
        items = _generic_search(q, tmdbid, tvdbid, imdbid)
        return _xml_response(_rss(items))
    return _xml_response(_rss([]))


# ---- search implementations ----

def _tv_search(q, tmdbid, tvdbid, imdbid, season, ep) -> list[dict]:
    tmdb_id = tmdbid or _tmdb_from_tvdb(tvdbid) or _tmdb_from_imdb(imdbid)
    if not tmdb_id and q:
        tmdb_id, title, year = _tmdb_search_tv(q)
    else:
        title, year = _tmdb_details("tv", tmdb_id) if tmdb_id else (q or "", "")

    if not tmdb_id:
        return []
    title = title or q or f"tmdb-{tmdb_id}"

    items: list[dict] = []
    if season is not None and ep is not None:
        items.append(_episode_release(tmdb_id, title, year, season, ep))
    elif season is not None:
        items.append(_season_pack_release(tmdb_id, title, year, season))
    else:
        # Whole-series: return a generic series release that the worker resolves.
        items.append(_series_release(tmdb_id, title, year))
    return items


def _movie_search(q, tmdbid, imdbid) -> list[dict]:
    tmdb_id = tmdbid or _tmdb_from_imdb(imdbid)
    if not tmdb_id and q:
        tmdb_id, title, year = _tmdb_search_movie(q)
    else:
        title, year = _tmdb_details("movie", tmdb_id) if tmdb_id else (q or "", "")
    if not tmdb_id:
        return []
    title = title or q or f"tmdb-{tmdb_id}"
    return [_movie_release(tmdb_id, title, year)]


def _generic_search(q, tmdbid, tvdbid, imdbid) -> list[dict]:
    out: list[dict] = []
    out += _tv_search(q, tmdbid, tvdbid, imdbid, None, None)
    out += _movie_search(q, tmdbid, imdbid)
    return out


# ---- release builders ----

def _episode_release(tmdb_id: str, title: str, year: str,
                     season: int, episode: int) -> dict:
    name = _release_name(title, year, season=season, episode=episode)
    magnet = make_magnet("tv", tmdb_id, title, season=season, episode=episode)
    return {
        "title": name,
        "guid": f"watchseries:tv:{tmdb_id}:s{season}e{episode}",
        "link": magnet,
        "size": SIZE_EPISODE,
        "category": CAT_TV,
        "pubDate": dt.datetime.now(dt.timezone.utc),
        "attrs": {"tmdb": tmdb_id, "season": season, "episode": episode},
    }


def _season_pack_release(tmdb_id: str, title: str, year: str, season: int) -> dict:
    name = _release_name(title, year, season=season)
    magnet = make_magnet("tv", tmdb_id, title, season=season)
    return {
        "title": name,
        "guid": f"watchseries:tv:{tmdb_id}:s{season}",
        "link": magnet,
        "size": SIZE_SEASON,
        "category": CAT_TV,
        "pubDate": dt.datetime.now(dt.timezone.utc),
        "attrs": {"tmdb": tmdb_id, "season": season},
    }


def _series_release(tmdb_id: str, title: str, year: str) -> dict:
    name = _release_name(title, year) + ".COMPLETE"
    magnet = make_magnet("tv", tmdb_id, title)
    return {
        "title": name,
        "guid": f"watchseries:tv:{tmdb_id}:all",
        "link": magnet,
        "size": SIZE_SEASON * 5,
        "category": CAT_TV,
        "pubDate": dt.datetime.now(dt.timezone.utc),
        "attrs": {"tmdb": tmdb_id},
    }


def _movie_release(tmdb_id: str, title: str, year: str) -> dict:
    name = _release_name(title, year, is_movie=True)
    magnet = make_magnet("movie", tmdb_id, title)
    return {
        "title": name,
        "guid": f"watchseries:movie:{tmdb_id}",
        "link": magnet,
        "size": SIZE_MOVIE,
        "category": CAT_MOVIE,
        "pubDate": dt.datetime.now(dt.timezone.utc),
        "attrs": {"tmdb": tmdb_id},
    }


def _release_name(title: str, year: str, *, season: int | None = None,
                  episode: int | None = None, is_movie: bool = False) -> str:
    base = title.replace(" ", ".")
    parts = [base]
    if year:
        parts.append(str(year))
    if not is_movie and season is not None and episode is not None:
        parts.append(f"S{season:02d}E{episode:02d}")
    elif not is_movie and season is not None:
        parts.append(f"S{season:02d}")
    parts += ["1080p", "WEBDL", "x264-WATCHSERIES"]
    return ".".join(parts)


# ---- TMDB lookups (optional, requires TMDB_API_KEY env var) ----

def _tmdb_api(path: str, params: dict[str, Any]) -> dict | None:
    key = os.environ.get("TMDB_API_KEY", "")
    if not key:
        return None
    params = {"api_key": key, **params}
    url = f"https://api.themoviedb.org/3{path}?{urllib.parse.urlencode(params)}"
    try:
        with urllib.request.urlopen(url, timeout=15) as r:
            import json
            return json.loads(r.read())
    except Exception:
        return None


def _tmdb_from_tvdb(tvdbid: str | None) -> str | None:
    if not tvdbid:
        return None
    d = _tmdb_api(f"/find/{tvdbid}", {"external_source": "tvdb_id"})
    if not d:
        return None
    results = d.get("tv_results", [])
    if results:
        return str(results[0]["id"])
    return None


def _tmdb_from_imdb(imdbid: str | None) -> str | None:
    if not imdbid:
        return None
    d = _tmdb_api(f"/find/{imdbid}", {"external_source": "imdb_id"})
    if not d:
        return None
    for k in ("tv_results", "movie_results"):
        if d.get(k):
            return str(d[k][0]["id"])
    return None


def _tmdb_search_tv(q: str) -> tuple[str | None, str, str]:
    d = _tmdb_api("/search/tv", {"query": q})
    if not d or not d.get("results"):
        return None, q, ""
    r = d["results"][0]
    return str(r["id"]), r.get("name", q), (r.get("first_air_date") or "")[:4]


def _tmdb_search_movie(q: str) -> tuple[str | None, str, str]:
    d = _tmdb_api("/search/movie", {"query": q})
    if not d or not d.get("results"):
        return None, q, ""
    r = d["results"][0]
    return str(r["id"]), r.get("title", q), (r.get("release_date") or "")[:4]


def _tmdb_details(kind: str, tmdb_id: str) -> tuple[str, str]:
    d = _tmdb_api(f"/{kind}/{tmdb_id}", {})
    if not d:
        return "", ""
    if kind == "tv":
        return d.get("name", ""), (d.get("first_air_date") or "")[:4]
    return d.get("title", ""), (d.get("release_date") or "")[:4]


# ---- XML rendering ----

def _xml_response(body: str) -> Response:
    return Response(content=body, media_type="application/rss+xml; charset=utf-8")


def _caps_xml() -> str:
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<caps>
  <server title="{escape(INDEXER_TITLE)}"/>
  <limits max="100" default="50"/>
  <searching>
    <search available="yes" supportedParams="q"/>
    <tv-search available="yes" supportedParams="q,tvdbid,tmdbid,imdbid,season,ep"/>
    <movie-search available="yes" supportedParams="q,tmdbid,imdbid"/>
  </searching>
  <categories>
    <category id="2000" name="Movies">
      <subcat id="2040" name="Movies/HD"/>
    </category>
    <category id="5000" name="TV">
      <subcat id="5040" name="TV/HD"/>
    </category>
  </categories>
</caps>
"""


def _rss(items: list[dict]) -> str:
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<rss version="2.0" xmlns:torznab="http://torznab.com/schemas/2015/feed">',
        '<channel>',
        f'<title>{escape(INDEXER_TITLE)}</title>',
        '<description>watchseries.bar via Torznab</description>',
        '<link>https://watchseries.bar/</link>',
    ]
    for it in items:
        parts.append(_rss_item(it))
    parts.append('</channel></rss>')
    return "\n".join(parts)


def _rss_item(it: dict) -> str:
    pub = format_datetime(it["pubDate"])
    enclosure_url = escape(it["link"])
    attrs = it.get("attrs", {})
    attr_xml = "".join(
        f'<torznab:attr name="{k}" value="{escape(str(v))}"/>'
        for k, v in attrs.items()
    )
    return f"""<item>
<title>{escape(it["title"])}</title>
<guid isPermaLink="false">{escape(it["guid"])}</guid>
<link>{enclosure_url}</link>
<pubDate>{pub}</pubDate>
<size>{it["size"]}</size>
<category>{escape(it["category"])}</category>
<enclosure url="{enclosure_url}" length="{it["size"]}" type="application/x-bittorrent"/>
<torznab:attr name="category" value="{escape(it["category"])}"/>
<torznab:attr name="size" value="{it["size"]}"/>
{attr_xml}
</item>"""
